import React from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'


function LoginId() {
  const router = useRouter()
  console.log(router)
  return (
    <>
      <Head>
        <title>Login detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div>login -{`>`} LoginId {router.query.id}</div>
    </>
  )
}

export default LoginId